### ISSUE TITLE
Modify its documentation process

### ISSUE THREAD

**Issue by kimhxsong** [kimhxsong/unixtack#1]
### PRESENT DOCUMENTS
- README.md
- SGIU.md
- UNIXTOOLS.md

### TODO
- [ ] Things pertaining to the shell script should be removed from the README.md
- [ ] SCRIPTS.md will be in charge of script-related information in the future.
- [ ] README.md will take care of the table of contents.

### DOCUMENTS FOLLOWING CHANGES
- README.md: table of contents and references
- SGIU.md: details of shell syntax used in scripting
- UNIXTOOLS.md: a list of unix command-line utilities to check
- SCRIPTS.md: indices and a quick description of shell scripts
